[build]
  command = "npm run build"
  publish = "dist"
  functions = "src/functions"

[build.environment]
  # cache Cypress binary in local "node_modules" folder
  # so Netlify caches it
  CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
  # set TERM variable for terminal output
  TERM = "xterm"

[dev]
  command = "npm run start"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# run Cypress E2E tests
[[plugins]]
package = "netlify-plugin-cypress"
  # run Cypress tests after deploy and record test results
  # to Cypress Dashboard
  [plugins.inputs]
    record = true
