[build]
  command = "npm run build"
  publish = "dist"
  functions = "src/functions"

[dev]
  command = "npm run start"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# run Cypress E2E tests
[[plugins]]
package = "netlify-plugin-cypress"
  [plugins.inputs]
    # skip the default tests before the deploy
    skip = true
  [plugins.inputs.onSuccess]
    # run tests after the deploy
    enable = true
