name: e2e
# https://docs.github.com/en/actions/reference/events-that-trigger-workflows
# https://docs.netlify.com/site-deploys/notifications/
on: [deployment, deployment_status]
jobs:
  show-event:
    runs-on: ubuntu-20.04
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
